<?php return [

	/* -------------- Pages --------------*/
	'site' => __DIR__ . '/../../blueprints/site.yml',
	'pages/article' => __DIR__ . '/../../blueprints/pages/article.yml',
	'pages/category' => __DIR__ . '/../../blueprints/pages/category.yml',
	'pages/error' => __DIR__ . '/../../blueprints/pages/error.yml',
	'pages/home' => __DIR__ . '/../../blueprints/pages/home.yml',

	/* -------------- Tabs --------------*/
	'tabs/backgroundimage' => __DIR__ . '/../../blueprints/tabs/backgroundimage.yml',
	'tabs/content' => __DIR__ . '/../../blueprints/tabs/content.yml',
	'tabs/image' => __DIR__ . '/../../blueprints/tabs/image.yml',
	'tabs/home' => __DIR__ . '/../../blueprints/tabs/home.yml',
	'tabs/legal' => __DIR__ . '/../../blueprints/tabs/legal.yml',
	'tabs/project' => __DIR__ . '/../../blueprints/tabs/project.yml',
	'tabs/properties' => __DIR__ . '/../../blueprints/tabs/properties.yml',
	'tabs/settings' => __DIR__ . '/../../blueprints/tabs/settings.yml',
	'tabs/site' => __DIR__ . '/../../blueprints/tabs/site.yml',
	'tabs/structure' => __DIR__ . '/../../blueprints/tabs/structure.yml',
	'tabs/video' => __DIR__ . '/../../blueprints/tabs/video.yml',
	'tabs/video-accessibility' => __DIR__ . '/../../blueprints/tabs/video-accessibility.yml',
	'tabs/video-player' => __DIR__ . '/../../blueprints/tabs/video-player.yml',

	/* -------------- Blocks --------------*/
	'blocks/pwButtons' => __DIR__ . '/../../blueprints/blocks/buttons/index.yml',
	'blocks/pwButton' => __DIR__ . '/../../blueprints/blocks/buttons/item.yml',
	'blocks/pwFooter' => __DIR__ . '/../../blueprints/blocks/footer/index.yml',
	'blocks/pwFooterItem' => __DIR__ . '/../../blueprints/blocks/footer/item.yml',

	/* -------------- Fields --------------*/
	'pagewizard/fields/address' => __DIR__ . '/../../blueprints/fields/address.yml',
	'pagewizard/fields/address-country' => __DIR__ . '/../../blueprints/fields/address-country.yml',
	'pagewizard/fields/address-email' => __DIR__ . '/../../blueprints/fields/address-email.yml',
	'pagewizard/fields/address-fax' => __DIR__ . '/../../blueprints/fields/address-fax.yml',
	'pagewizard/fields/address-name' => __DIR__ . '/../../blueprints/fields/address-name.yml',
	'pagewizard/fields/address-phone' => __DIR__ . '/../../blueprints/fields/address-phone.yml',
	'pagewizard/fields/address-whatsapp' => __DIR__ . '/../../blueprints/fields/address-whatsapp.yml',
	'pagewizard/fields/author' => __DIR__ . '/../../blueprints/fields/author.yml',
	'pagewizard/fields/background-color' => __DIR__ . '/../../blueprints/fields/background-color.yml',
	'pagewizard/fields/background-image' => __DIR__ . '/../../blueprints/fields/background-image.yml',
	'pagewizard/fields/background-size' => __DIR__ . '/../../blueprints/fields/background-size.yml',
	'pagewizard/fields/button-style' => __DIR__ . '/../../blueprints/fields/button-style.yml',
	'pagewizard/fields/copyright' => __DIR__ . '/../../blueprints/fields/copyright.yml',
	'pagewizard/fields/customtheme' => __DIR__ . '/../../blueprints/fields/customtheme.yml',
	'pagewizard/fields/fragment' => __DIR__ . '/../../blueprints/fields/fragment.yml',
	'pagewizard/fields/grid-offset' => __DIR__ . '/../../blueprints/fields/grid-offset.yml',
	'pagewizard/fields/grid-size' => __DIR__ . '/../../blueprints/fields/grid-size.yml',
	'pagewizard/fields/heading' => __DIR__ . '/../../blueprints/fields/heading.yml',
	'pagewizard/fields/image' => __DIR__ . '/../../blueprints/fields/image.yml',
	'pagewizard/fields/image-aria-describedby' => __DIR__ . '/../../blueprints/fields/image-aria-describedby.yml',
	'pagewizard/fields/image-aria-label' => __DIR__ . '/../../blueprints/fields/image-aria-label.yml',
	'pagewizard/fields/image-caption' => __DIR__ . '/../../blueprints/fields/image-caption.yml',
	'pagewizard/fields/image-crop' => __DIR__ . '/../../blueprints/fields/image-crop.yml',
	'pagewizard/fields/image-description' => __DIR__ . '/../../blueprints/fields/image-description.yml',
	'pagewizard/fields/image-ratio' => __DIR__ . '/../../blueprints/fields/image-ratio.yml',
	'pagewizard/fields/image-title' => __DIR__ . '/../../blueprints/fields/image-title.yml',
	'pagewizard/fields/image-type' => __DIR__ . '/../../blueprints/fields/image-type.yml',
	'pagewizard/fields/image-zoom' => __DIR__ . '/../../blueprints/fields/image-zoom.yml',
	'pagewizard/fields/images' => __DIR__ . '/../../blueprints/fields/images.yml',
	'pagewizard/fields/link-aria-describedby' => __DIR__ . '/../../blueprints/fields/link-aria-describedby.yml',
	'pagewizard/fields/link-aria-label' => __DIR__ . '/../../blueprints/fields/link-aria-label.yml',
	'pagewizard/fields/link-external' => __DIR__ . '/../../blueprints/fields/link-external.yml',
	'pagewizard/fields/link-internal' => __DIR__ . '/../../blueprints/fields/link-internal.yml',
	'pagewizard/fields/link-rel' => __DIR__ . '/../../blueprints/fields/link-rel.yml',
	'pagewizard/fields/link-target' => __DIR__ . '/../../blueprints/fields/link-target.yml',
	'pagewizard/fields/link-text' => __DIR__ . '/../../blueprints/fields/link-text.yml',
	'pagewizard/fields/link-type' => __DIR__ . '/../../blueprints/fields/link-type.yml',
	'pagewizard/fields/media-alignment' => __DIR__ . '/../../blueprints/fields/media-alignment.yml',
	'pagewizard/fields/media-copyright' => __DIR__ . '/../../blueprints/fields/media-copyright.yml',
	'pagewizard/fields/media-creator' => __DIR__ . '/../../blueprints/fields/media-creator.yml',
	'pagewizard/fields/media-credit' => __DIR__ . '/../../blueprints/fields/media-credit.yml',
	'pagewizard/fields/media-license' => __DIR__ . '/../../blueprints/fields/media-license.yml',
	'pagewizard/fields/media-position' => __DIR__ . '/../../blueprints/fields/media-position.yml',
	'pagewizard/fields/media-size' => __DIR__ . '/../../blueprints/fields/media-size.yml',
	'pagewizard/fields/media-source' => __DIR__ . '/../../blueprints/fields/media-source.yml',
	'pagewizard/fields/media-type' => __DIR__ . '/../../blueprints/fields/media-type.yml',
	'pagewizard/fields/meta-author' => __DIR__ . '/../../blueprints/fields/meta-author.yml',
	'pagewizard/fields/meta-description' => __DIR__ . '/../../blueprints/fields/meta-description.yml',
	'pagewizard/fields/meta-keywords' => __DIR__ . '/../../blueprints/fields/meta-keywords.yml',
	'pagewizard/fields/meta-pagetitle' => __DIR__ . '/../../blueprints/fields/meta-pagetitle.yml',
	'pagewizard/fields/meta-teaser' => __DIR__ . '/../../blueprints/fields/meta-teaser.yml',
	'pagewizard/fields/seo-canonical' => __DIR__ . '/../../blueprints/fields/seo-canonical.yml',
	'pagewizard/fields/seo-robots' => __DIR__ . '/../../blueprints/fields/seo-robots.yml',
	'pagewizard/fields/style' => __DIR__ . '/../../blueprints/fields/style.yml',
	'pagewizard/fields/tagline' => __DIR__ . '/../../blueprints/fields/tagline.yml',
	'pagewizard/fields/text-color' => __DIR__ . '/../../blueprints/fields/text-color.yml',
	'pagewizard/fields/text-markdown' => __DIR__ . '/../../blueprints/fields/text-markdown.yml',
	'pagewizard/fields/text-mode' => __DIR__ . '/../../blueprints/fields/text-mode.yml',
	'pagewizard/fields/text-quote' => __DIR__ . '/../../blueprints/fields/text-quote.yml',
	'pagewizard/fields/text-textarea' => __DIR__ . '/../../blueprints/fields/text-textarea.yml',
	'pagewizard/fields/text-writer' => __DIR__ . '/../../blueprints/fields/text-writer.yml',
	'pagewizard/fields/toggle-spacing' => __DIR__ . '/../../blueprints/fields/toggle-spacing.yml',
	'pagewizard/fields/video' => __DIR__ . '/../../blueprints/fields/video.yml',
	'pagewizard/fields/video-aria-describedby' => __DIR__ . '/../../blueprints/fields/video-aria-describedby.yml',
	'pagewizard/fields/video-aria-label' => __DIR__ . '/../../blueprints/fields/video-aria-label.yml',
	'pagewizard/fields/video-audiodescription' => __DIR__ . '/../../blueprints/fields/video-audiodescription.yml',
	'pagewizard/fields/video-autoplay' => __DIR__ . '/../../blueprints/fields/video-autoplay.yml',
	'pagewizard/fields/video-caption' => __DIR__ . '/../../blueprints/fields/video-caption.yml',
	'pagewizard/fields/video-chapters' => __DIR__ . '/../../blueprints/fields/video-chapters.yml',
	'pagewizard/fields/video-controls' => __DIR__ . '/../../blueprints/fields/video-controls.yml',
	'pagewizard/fields/video-description' => __DIR__ . '/../../blueprints/fields/video-description.yml',
	'pagewizard/fields/video-loop' => __DIR__ . '/../../blueprints/fields/video-loop.yml',
	'pagewizard/fields/video-muted' => __DIR__ . '/../../blueprints/fields/video-muted.yml',
	'pagewizard/fields/video-poster' => __DIR__ . '/../../blueprints/fields/video-poster.yml',
	'pagewizard/fields/video-preload' => __DIR__ . '/../../blueprints/fields/video-preload.yml',
	'pagewizard/fields/video-ratio' => __DIR__ . '/../../blueprints/fields/video-ratio.yml',
	'pagewizard/fields/video-source' => __DIR__ . '/../../blueprints/fields/video-source.yml',
	'pagewizard/fields/video-subtitle' => __DIR__ . '/../../blueprints/fields/video-subtitle.yml',
	'pagewizard/fields/video-title' => __DIR__ . '/../../blueprints/fields/video-title.yml',
	'pagewizard/fields/video-transcript' => __DIR__ . '/../../blueprints/fields/video-transcript.yml',
	'pagewizard/fields/video-url' => __DIR__ . '/../../blueprints/fields/video-url.yml',

	/* -------------- Headlines --------------*/
	'pagewizard/headlines/accessibility' => __DIR__ . '/../../blueprints/headlines/accessibility.yml',
	'pagewizard/headlines/blockcontent' => __DIR__ . '/../../blueprints/headlines/blockcontent.yml',
	'pagewizard/headlines/blockproperties' => __DIR__ . '/../../blueprints/headlines/blockproperties.yml',
	'pagewizard/headlines/contact' => __DIR__ . '/../../blueprints/headlines/contact.yml',
	'pagewizard/headlines/content' => __DIR__ . '/../../blueprints/headlines/content.yml',
	'pagewizard/headlines/copyrights' => __DIR__ . '/../../blueprints/headlines/copyrights.yml',
	'pagewizard/headlines/editorsettings' => __DIR__ . '/../../blueprints/headlines/editorsettings.yml',
	'pagewizard/headlines/fieldsettings' => __DIR__ . '/../../blueprints/headlines/fieldsettings.yml',
	'pagewizard/headlines/footer' => __DIR__ . '/../../blueprints/headlines/footer.yml',
	'pagewizard/headlines/grid' => __DIR__ . '/../../blueprints/headlines/grid.yml',
	'pagewizard/headlines/image' => __DIR__ . '/../../blueprints/headlines/image.yml',
	'pagewizard/headlines/imagesettings' => __DIR__ . '/../../blueprints/headlines/imagesettings.yml',
	'pagewizard/headlines/layout' => __DIR__ . '/../../blueprints/headlines/layout.yml',
	'pagewizard/headlines/layoutsettings' => __DIR__ . '/../../blueprints/headlines/layoutsettings.yml',
	'pagewizard/headlines/license' => __DIR__ . '/../../blueprints/headlines/license.yml',
	'pagewizard/headlines/link' => __DIR__ . '/../../blueprints/headlines/link.yml',
	'pagewizard/headlines/meta' => __DIR__ . '/../../blueprints/headlines/meta.yml',
	'pagewizard/headlines/player' => __DIR__ . '/../../blueprints/headlines/player.yml',
	'pagewizard/headlines/preview' => __DIR__ . '/../../blueprints/headlines/preview.yml',
	'pagewizard/headlines/properties' => __DIR__ . '/../../blueprints/headlines/properties.yml',
	'pagewizard/headlines/seo' => __DIR__ . '/../../blueprints/headlines/seo.yml',
	'pagewizard/headlines/slideshow' => __DIR__ . '/../../blueprints/headlines/slideshow.yml',
	'pagewizard/headlines/spacing' => __DIR__ . '/../../blueprints/headlines/spacing.yml',
	'pagewizard/headlines/subtitles' => __DIR__ . '/../../blueprints/headlines/subtitles.yml',
	'pagewizard/headlines/theme' => __DIR__ . '/../../blueprints/headlines/theme.yml',
	'pagewizard/headlines/video' => __DIR__ . '/../../blueprints/headlines/video.yml',

	/* -------------- Files --------------*/
	'files/pwBackgroundimage' => __DIR__ . '/../../blueprints/files/backgroundimage.yml',
	'files/pwImage' => __DIR__ . '/../../blueprints/files/image.yml',
	'files/pwVideo' => __DIR__ . '/../../blueprints/files/video.yml',
	'files/pwVideoPoster' => __DIR__ . '/../../blueprints/files/poster.yml',
];