---
label: kdpages.tab.project
icon: settings
columns:
  - width: 3/4
    sections:
      project:
        type: fields
        fields:
          headlineMeta:
            extends: kirbyfields/headlines/meta
          publisher:
            extends: kirbyfields/fields/publisher
          footer:
            type: blocks
            max: 4
            label: kdpages.field.footer
            empty: kdpages.field.footer.empty
            fieldsets:
              - footer
          socialmedia:
            type: blocks
            label: kdpages.field.socialmedia
            empty: kdpages.field.socialmedia.empty
            fieldsets:
              - socialmedia




  - width: 1/4
    sections:
      address:
        type: fields
        fields:
          headlineAddress:
            extends: kirbyfields/headlines/address
          addressName:
            extends: kirbyfields/fields/address-name
          address:
            extends: kirbyfields/fields/address
          addressPhone:
            extends: kirbyfields/fields/address-phone
          addressEmail:
            extends: kirbyfields/fields/address-email
          copyright:
            extends: kirbyfields/fields/copyright