---
label: pagewizard.tab.project
icon: settings
columns:
  - width: 3/4
    sections:
      project:
        type: fields
        fields:
          headlineMeta:
            extends: pagewizard/headlines/meta
          publisher:
            extends: pagewizard/fields/publisher
          footer:
            type: blocks
            max: 4
            label: pagewizard.footer
            empty: pagewizard.footer.empty
            fieldsets:
              - footer
          socialmedia:
            type: object
            label: pagewizard.field.socialmedia
            empty: pagewizard.field.socialmedia.empty
            fields:
              bluesky:
                type: url
                label: Bluesky
                placeholder: https://bsky.app/profile/{{ site.title }}
              codepen:
                type: url
                placeholder: https://codepen.io/{{ site.title }}
              facebook:
                type: url
                placeholder: https://facebook.com/{{ site.title }}
              github:
                type: url
                placeholder: https://github.com/{{ site.title }}
              instagram:
                type: url
                placeholder: https://instagram.com/{{ site.title }}
              linkedin:
                type: url
                placeholder: https://linkedin.com/in/{{ site.title }}
              mastodon:
                type: url
                placeholder: https://mastodon.social/@{{ site.title }}
              threads:
                type: url
                placeholder: https://threads.net/@{{ site.title }}
              x:
                type: url
                placeholder: https://x.com/{{ site.title }}
              xing:
                type: url
                placeholder: https://xing.com/profile/{{ site.title }}
              youtube:
                type: url
                placeholder: https://youtube.com/@{{ site.title }}
  - width: 1/4
    sections:
      address:
        type: fields
        fields:
          headlineAddress:
            extends: pagewizard/headlines/address
          addressName:
            extends: pagewizard/fields/address-name
          address:
            extends: pagewizard/fields/address
          addressPhone:
            extends: pagewizard/fields/address-phone
          addressEmail:
            extends: pagewizard/fields/address-email
          copyright:
            extends: pagewizard/fields/copyright