---
label: pw.tab.project
icon: settings
columns:
  - width: 2/3
    sections:
      project:
        type: fields
        fields:
          headlineFooter:
            extends: pagewizard/headlines/footer
          footer:
            type: blocks
            max: 4
            label: pw.footer
            empty: pw.footer.empty
            fieldsets:
              - pwFooter
          copyright:
            extends: pagewizard/fields/copyright
  - width: 1/3
    sections:
      address:
        type: fields
        fields:
          headlineContact:
            extends: pagewizard/headlines/contact
          address:
            type: object
            label: pw.field.address
            empty: pw.field.address.empty
            help: pw.field.address.help
            fields:
              addressName:
                extends: pagewizard/fields/address-name
              address:
                extends: pagewizard/fields/address
              addressPhone:
                extends: pagewizard/fields/address-phone
              addressEmail:
                extends: pagewizard/fields/address-email
              addressCountry:
                extends: pagewizard/fields/address-country
          socialmedia:
            type: object
            label: pw.field.socialmedia
            empty: pw.field.socialmedia.empty
            help: pw.field.socialmedia.help
            fields:
              bluesky:
                type: url
                label: Bluesky
                placeholder: https://bsky.app/profile/{{ site.title }}
                help: https://bsky.app/
              codepen:
                type: url
                placeholder: https://codepen.io/{{ site.title }}
                help: https://codepen.io/
              facebook:
                type: url
                placeholder: https://facebook.com/{{ site.title }}
                help: https://facebook.com/
              github:
                type: url
                placeholder: https://github.com/{{ site.title }}
                help: https://github.com/
              instagram:
                type: url
                placeholder: https://instagram.com/{{ site.title }}
                help: https://instagram.com/
              linkedin:
                type: url
                placeholder: https://linkedin.com/in/{{ site.title }}
                help: https://linkedin.com/
              mastodon:
                type: url
                placeholder: https://mastodon.social/@{{ site.title }}
                help: https://mastodon.social/
              threads:
                type: url
                placeholder: https://threads.net/@{{ site.title }}
                help: https://threads.net/
              x:
                type: url
                placeholder: https://x.com/{{ site.title }}
                help: https://x.com/
              xing:
                type: url
                placeholder: https://xing.com/profile/{{ site.title }}
                help: https://xing.com/
              youtube:
                type: url
                placehhttps://youtube.com/@older: https://youtube.com/@{{ site.title }}
                help: https://youtube.com/