---
label: pagewizard.tab.project
icon: settings
columns:
  - width: 2/3
    sections:
      project:
        type: fields
        fields:
          headlineFooter:
            extends: pagewizard/headlines/footer
          footer:
            type: blocks
            max: 4
            label: pagewizard.footer
            empty: pagewizard.footer.empty
            fieldsets:
              - footer
          copyright:
            extends: pagewizard/fields/copyright
  - width: 1/3
    sections:
      address:
        type: fields
        fields:
          headlineContact:
            extends: pagewizard/headlines/contact
          address:
            type: object
            label: pagewizard.field.address
            empty: pagewizard.field.address.empty
            fields:
              headlineAddress:
                extends: pagewizard/headlines/address
              addressName:
                extends: pagewizard/fields/address-name
              address:
                extends: pagewizard/fields/address
              addressPhone:
                extends: pagewizard/fields/address-phone
              addressEmail:
                extends: pagewizard/fields/address-email
              addressCountry:
                extends: pagewizard/fields/address-country
          socialmedia:
            type: object
            label: pagewizard.object.socialmedia
            empty: pagewizard.object.socialmedia.empty
            fields:
              headlineSocialmedia:
                extends: pagewizard/headlines/socialmedia
              bluesky:
                type: url
                label: Bluesky
                placeholder: https://bsky.app/profile/{{ site.title }}
              codepen:
                type: url
                placeholder: https://codepen.io/{{ site.title }}
              facebook:
                type: url
                placeholder: https://facebook.com/{{ site.title }}
              github:
                type: url
                placeholder: https://github.com/{{ site.title }}
              instagram:
                type: url
                placeholder: https://instagram.com/{{ site.title }}
              linkedin:
                type: url
                placeholder: https://linkedin.com/in/{{ site.title }}
              mastodon:
                type: url
                placeholder: https://mastodon.social/@{{ site.title }}
              threads:
                type: url
                placeholder: https://threads.net/@{{ site.title }}
              x:
                type: url
                placeholder: https://x.com/{{ site.title }}
              xing:
                type: url
                placeholder: https://xing.com/profile/{{ site.title }}
              youtube:
                type: url
                placeholder: https://youtube.com/@{{ site.title }}