---
label: kdpages.tab.site
icon: home
columns:
  - width: 2/3
    sections:
      listed:
        label: kdpages.section.listed
        type: pages
        status: listed
        templates: ["article","category"]
        layout: cardlets
        image: icon
        text: '{{ page.title }}'
  - width: 1/3
    sections:
      unlisted:
        label: kdpages.section.unlisted
        type: pages
        status: unlisted
        templates: ["article","category","error","home"]
        flip: true
        image: icon
        text: '{{ page.title }}'
      draft:
        label: kdpages.section.draft
        type: pages
        status: draft
        templates: ["article","category"]
        image: icon
        text: '{{ page.title }}'